<?php
/**
 * @var array $articles -- Список всех статей
 * @var boolean $canEdit -- Право редактировать статьи
 * @var boolean $canDelete -- Право удалять статьи
 */
?>
<section class="articles">
	<form action="/articles/create" method="get">
		<input type="submit" value="Создать статью" class="btn">
	</form>
	<?php if (!empty($articles)) { ?>
		<?php
		/** @var \Model\Articles\Article $article */
		foreach ($articles as $article) { ?>
			<div class="article">
				<div class="article-title">
					<?=$article->getTitle()?>
				</div>
				<div class="article-content">
					<?php if (!empty($article->getContent())) echo $article->getPreviewText() . '...'; else echo '&nbsp;'; ?>
				</div>
				<div class="article-actions">
					<form action="/articles/edit" method="get">
						<input type="hidden" name="article" value="<?=$article->getId()?>">
						<?php if ($canEdit) { ?>
							<input type="submit" value="Редактировать" class="btn">
						<?php } ?>
					</form>
					<form action="/articles/delete" method="post" class="delete-article-form" id="delete-article-form-<?=$article->getId()?>">
						<input type="hidden" name="article" value="<?=$article->getId()?>">
						<?php if ($canDelete) { ?>
							<div class="btn cancel">Удалить</div>
							<input type="submit" value="" style="display: none;">
						<?php } ?>
					</form>
				</div>
			</div>
		<?php } ?>
	<?php } ?>
</section>