<?php
/**
 * @var $articles array -- Список всех статей
 * @var $permissions array -- Права, которые есть у пользователя, на операции со статьями
 */
?>
<section class="articles">
	<?php if (in_array('create_article', $permissions)) { ?>
		<form action="/article/create" method="get">
			<input type="submit" value="Создать статью" class="btn">
		</form>
	<?php } ?>
	<?php if (!empty($articles)) { ?>
		<?php foreach ($articles as $article) { ?>
			<div class="article">
				<div class="article-title">
					<?=$article['title']?>
				</div>
				<div class="article-content">
					<?php if (!empty($article['content'])) echo $article['content']; else echo '&nbsp;'; ?>
				</div>
				<div class="edit-article">
					<form action="/article/<?=$article['id']?>/edit" method="get">
						<?php if (in_array('edit_article', $permissions)) { ?>
							<input type="submit" value="Редактировать" class="btn">
						<?php } ?>
						
						<?php if (in_array('delete_article', $permissions)) { ?>
							<input type="submit" value="Удалить" class="btn cancel">
						<?php } ?>
					</form>
				</div>
			</div>
		<?php } ?>
	<?php } ?>
</section>