<!doctype html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Авторизация</title>
</head>
<body>
<form action="/login/send" method="post">
	<?php  ?>
	<label for="login">
		<input type="text" id="login" name="login" placeholder="Логин" <?php if (!empty($login)) echo "value=\"$login\"" ?>>
	</label>
	<label for="pass">
		<input type="password" id="pass" name="password" placeholder="Пароль">
	</label>
	<label for="submit">
		<input type="submit" value="Авторизоваться">
	</label>
</form>
</body>
</html>