<?php
/**
 * Defining variables used in html.
 *
 * @var $title string
 * @var $content string
 */
?>
<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $title ?></title>
		<meta charset="utf-8"/>
		<meta name="description" content="This is the main page of my site"/>
		<link rel="stylesheet" href="/web/css/style.css" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Comfortaa:400,300,700&subset=latin,cyrillic,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'/>
	</head>
	<body>
		<div class="content">
			<ul class="main-menu">
				<li>
					<h1><a href="#">Home</a></h1>
				</li>
				<li><a href="#">Статьи</a></li>
				<li><a href="#">Каталог</a></li>
				<li class="here"><a href="#">Галерея изображений</a></li>
				<li><a href="#">Регистрация</a></li>
				<li><a href="#">Контакты</a></li>
			</ul>
			<section>
				<?php echo $content ?>
			</section>
		</div>
		<footer>
			All rights reserved &copy; 2015
		</footer>
	</body>
</html>