<!doctype html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Создание новой статьи</title>
</head>
<body>
	<form action="/article/create/send" method="post" id="new-article-form">
		<label for="title">
			Заголовок статьи
			<input type="text" name="title" id="title">
		</label>
		<br/>
		<label for="content">
			Содержимое
			<textarea name="content" id="content" cols="30" rows="10"></textarea>
		</label>
		<br/>
		<input type="submit" value="Сохранить">
	</form>
</body>
</html>