ALTER TABLE users
  ADD COLUMN surname VARCHAR(50) DEFAULT NULL AFTER email,
  ADD COLUMN names VARCHAR(128) NOT NULL AFTER surname;

ALTER TABLE roles
    ADD COLUMN role_title VARCHAR(64) DEFAULT NULL;