CREATE DATABASE blog;

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(50) NOT NULL,
  email VARCHAR(50) DEFAULT NULL,
  role_id INT(3) NOT NULL,
  CONSTRAINT FOREIGN KEY role_ref (role_id) REFERENCES roles (id) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT DEFAULT NULL,
  author INT NOT NULL,
  date_created TIMESTAMP DEFAULT current_timestamp,
  CONSTRAINT FOREIGN KEY user_ref (author) REFERENCES users (id) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  article_id INT NOT NULL,
  author int NOT NULL,
  content TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT current_timestamp,
  CONSTRAINT FOREIGN KEY user_ref (author) REFERENCES users (id) ON UPDATE CASCADE,
  CONSTRAINT FOREIGN KEY article_ref (article_id) REFERENCES articles (id) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS article_tags (
  article_id INT NOT NULL,
  tag_id INT NOT NULL ,
  PRIMARY KEY (article_id, tag_id),
  CONSTRAINT FOREIGN KEY article_ref (article_id) REFERENCES articles (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FOREIGN KEY tag_ref (tag_id) REFERENCES tags (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE comments;
DROP TABLE article_tags;
DROP TABLE tags;
DROP TABLE articles;
DROP TABLE users;
DROP TABLE roles;

# Add default role
INSERT INTO roles VALUES (0, 'anonymous');
UPDATE roles SET id = 0;

# Add default user
INSERT INTO users VALUES (0, 'anon', '123456', 'anonymous@gmail.com', 0);
UPDATE users SET id = 0;
